### ISSUE TITLE
Problems with 2.2.0

### ISSUE THREAD

**Issue by cwelk** [Appboy/appboy-cordova-sdk#13]
Hi,

Since the 2.2.0 release we observed two problems:

1) 
We no longer can see in app messages with an image on iOS. Device log prints:
`[APPBOY] SDWebImageManager doesn't respond to selector downloadImageWithURL:options:progress:completed:. Appboy depends on SDWebImage 3.x, please check your SDWebImage version.`
(To make sure it's not related to another plugin I also tried with a blank cordova app containing only the appboy plugin)

2)
On Android in app messages don't show at all. Event tracking is working without problems and the user is correctly attributed in appboy. There are no device error logs appearing. 
(To make sure it's not related to another plugin I also tried with a blank cordova app containing only the appboy plugin)

Our setup is:
```
cordova 6.5.0
cordova-android 6.1.2
cordova-ios 4.3.1
iOS deployment target 8.0 (also tried higher versions)
android:minSdkVersion="15" 
android:targetSdkVersion="23"
```

**Comment by radixdev** [comment]
Hi @cwelk, 

For iOS, thank you for surfacing this bug, we have a Cordova release planned very shortly to fix this. Please see the [AppboyKit changelog](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md) for more details.

For Android, I could not reproduce the issue. To help debug this:

1. Can you provide debug level logs? This can be done via the following preference in your config.xml file:
`<preference name="com.appboy.android_log_level" value="0" />` 
2. Can you share your testing procedure? I.e. clearing the app -> sending a test in-app message -> verifying it doesn't display, etc.
3. Can you provide a link to an example Android project where in-app messages are not displaying? 

Thank you,
Julian

**Comment by cwelk** [comment]
Hi @radixdev 

Sorry for the delayed response, and thanks for helping in this matter.

Regarding the android bug:

1.  See the logfile https://raw.githubusercontent.com/cwelk/appboy_android_test/master/log.txt

2. Testing procedure was: Having a blank cordova project, with only appboy cordova as addition. Then add the android platform. In the JS on `$ionicPlatform.ready` I change the user and send a custom event. I stop and resume the appboy campaign. The campaign is configured to show once a session is started or the custom event is fired. Target users are restricted to User ID. And I see the campaign being sent in the campaign overview counter but it doesn't show in the app.

3. I prepared a sample project which also behaves like described https://github.com/cwelk/appboy_android_test

Thank you,
Christian

**Comment by radixdev** [comment]
From looking at the android logs and testing with the sample project, it appears that no in-app messages are being sent to the device (see [this line](https://github.com/cwelk/appboy_android_test/blob/master/log.txt#L116)). This could be that the campaign isn't properly targeting the user '1ve2q'. 

1. Can you post a link to your campaign in the appboy dashboard so I debug further?
2. Just for testing, can you set each user to be re-eligible to receive the campaign? This is found in "campaign" -> ""delivery" -> "delivery controls" and set the value to 0.

Thanks,
Julian

**Comment by cwelk** [comment]
1. https://dashboard.appboy.com/engagement/campaigns/58dbc2a55c5a687663452d8f/577a3b8a56ec3147cb292649?campaignName=Copy%20of%20phv_dynamic_link&page=-2

2. Yes it was already configured that way.

But strangely with the 2.1.0 cordova plugin the message gets displayed. And regardless of the message being shown (2.1.0) or not (2.2.0) them sent counter, displayed in the appboy dashboard, is raised in both cases.

Thanks,
Christian

**Comment by radixdev** [comment]
Hey @cwelk,

Just as an update, I've raised this issue with our backend team and will get back to you once I know more. The campaign you were testing with and a test campaign I created both did not send. 

Thanks,
Julian

**Comment by radixdev** [comment]
Hey @cwelk,

We just updated the Cordova SDK to version 2.3.0. The release includes a fix for the iOS in-app message `SDWebImageManager` issue and the Android original in-app message issue you were seeing. Please let me know if the release fixes the issues you were experiencing and thank you for raising them with us!

Thanks,
Julian

**Comment by cwelk** [comment]
Hi @radixdev,

Both Issues (iOS/Android) are no longer reproducable with the new cordova release. Thank you for the quick and professional help!

Thanks,
Christian
