### ISSUE TITLE
Notification click handling

### ISSUE THREAD

**Issue by Jeremlicious** [Appboy/appboy-cordova-sdk#17]
The SDK does not handle clicks on notification. The app should open when I click on the notification.
We made a commit to fix that on Android in our fork
https://github.com/Loisirsencheres/appboy-cordova-sdk/commits/master

We don't know how to pass deeplinks and triger action from click on notification. It seems that it is not implemented.

We also made a commit to make the Appboy SDK compatible with Ionic3

**Comment by radixdev** [comment]
Hey @Jeremlicious ,

Thank you for bringing up the Ionic3 compatibility and producing a fix. We should have a release containing those changes in the near future. 

1. Can you share any steps to reproduce the notification clicks not being followed on Android? A sample app would help greatly here.
2. What are the contents of your `config.xml` as [specified here?](https://www.appboy.com/documentation/Cordova/Android_and_FireOS/#configure-the-plugin)
3. Is this issue only happening on Android?
4. For any testing of the above, can you share any verbose logcat logs produced when the notification gets clicked? You can set the log to verbose via setting `"com.appboy.android_log_level"` to `0` in your `config.xml`

Thanks,
Julian

**Comment by Jeremlicious** [comment]
Hi @radixdev yes there are many other forks for Ionic3.

Concerning the push notification we do receive them from the Braze interface but it seems that appboy-cordova-sdk does not even provide the feature of clicking on the notification. One of our developer implemented this feature here : 
https://github.com/Loisirsencheres/appboy-cordova-sdk/commit/0dd7cdb3140af1026a0d6e9884e7ee26ef4444c6 `[FEATURE] open app when clicking on plugin` using a BroadcastReceiver.
However we don't have the capacity to continue implementing new Feature on your SDK. We need to be able to open the app via deeplinks in push.

What about iOS ? We are not there yet but are deeplinking in push implemented in your SDK ?
It seems that deeplinking is a basic feature in the Braze interface.

In case you need technical information we published a blanck Ionic  project : https://github.com/Loisirsencheres/ionic3-example

We can also send some details in private.
Cheers.

**Comment by Jeremlicious** [comment]
Hi @radixdev, any update on this ? Is it possible that you talk to Rocky Lotito in order for you to allocate some time to implement these features ?

**Comment by Jeremlicious** [comment]
Hi, have since swiched from Ionic / Cordova to native.
Good luck.

**Comment by radixdev** [comment]
Hey @Jeremlicious ,

I'm closing this issue for now.

**Comment by xueligoh** [comment]
Hi @radixdev, would like to clarify if the opening behaviour of the app when clicked on the notification is available or unavailable in the plugin?
