### ISSUE TITLE
Push registration - Manual call

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#20]
Hi @radixdev,

**Platform iOS:** We are planning to ask the push registration permission with a button tap. So basically we want to disable the automatic feature that comes with the plugin. 

We have found below:
<preference name="com.appboy.ios_disable_automatic_push_registration" value="false" />

On iOS we can trigger this only once, so we need to ask for this permission on the right section of the app. 

Can we simply call (what parameters we can pass?): **registerAppboyPushMessages()** 

Please advise.

**Comment by radixdev** [comment]
Hello @asangadev , 

To disable automatic iOS push registration, please follow https://www.braze.com/documentation/Cordova/iOS/#removing-automatic-push-setup-ios. 
To manually register for iOS push notifications, follow the steps outlined via https://www.braze.com/documentation/iOS/#step-3-register-for-push-notifications.

Let us know if these steps work for you.

**Comment by asangadev** [comment]
Hi @radixde,

Thanks for getting back to us. Is there any Javascript method (that we can trigger the core function)? We would like to control this via Javascript. 

Cheers!

**Comment by radixdev** [comment]
We do not have a way to manually request the push permission via the javascript plugin. You'll have to modify the plugin to allow for the manual registration to occur via Javascript.

**Comment by radixdev** [comment]
You'll have to email support@braze.com to guide you through the migration.

For the manual push call:

0. Clone the cordova plugin to make these plugin changes and import that modified version into your project.
1. Remove the automatic prompt from https://github.com/Appboy/appboy-cordova-sdk/blob/master/src/ios/AppboyPlugin.m#L45-L65
2. Update the [AppboyPlugin.js](https://github.com/Appboy/appboy-cordova-sdk/blob/master/www/AppboyPlugin.js) to add a `show push prompt` or equivalent method. I.e.
```
AppboyPlugin.prototype.iosShowPushPrompt = function () {
	cordova.exec(null, null, "AppboyPlugin", "iosShowPushPrompt", []);
}
```

3. Update the `AppboyPlugin.m` file to implement the `iosShowPushPrompt` method.

```
- (void)iosShowPushPrompt:(CDVInvokedUrlCommand *)command {
    UIUserNotificationType notificationSettingTypes = (UIUserNotificationTypeBadge | UIUserNotificationTypeAlert | UIUserNotificationTypeSound);
    if (floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_9_x_Max) {
      UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
      // If the delegate hasn't been set yet, set it here in the plugin
      if (center.delegate == nil) {
        center.delegate = [UIApplication sharedApplication].delegate;
      }
      [center requestAuthorizationWithOptions:(UNAuthorizationOptionAlert | UNAuthorizationOptionSound | UNAuthorizationOptionBadge)
                            completionHandler:^(BOOL granted, NSError * _Nullable error) {
                              NSLog(@"Permission granted.");
      }];
      [[UIApplication sharedApplication] registerForRemoteNotifications];
    } else if (floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_7_1) {
      UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:notificationSettingTypes categories:nil];
      [[UIApplication sharedApplication] registerForRemoteNotifications];
      [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
    } else {
      [[UIApplication sharedApplication] registerForRemoteNotificationTypes: notificationSettingTypes];
    }
}
``` 

4. At this point, you should be able to call `iosShowPushPrompt` on the appboy plugin via javascript to show the push prompt

**Comment by asangadev** [comment]
I have setup a separate repo: https://github.com/asangadev/appboy-cordova-sdk/commit/0a5800b3868434da37713ba6bd3d564e09b455aa

Cheers!

**Comment by asangadev** [comment]
Hi @radixdev ,

Could you please help us with below?

![screen shot 2018-05-01 at 11 41 02 am](https://user-images.githubusercontent.com/16328655/39458024-0639b94a-4d35-11e8-9170-257955341c41.png)

**Comment by radixdev** [comment]
Move that function bracket on [line 67](https://github.com/asangadev/appboy-cordova-sdk/blob/master/src/ios/AppboyPlugin.m#L67) to be above the method definition. Currently you have a method within another method.
