### ISSUE TITLE
iOS build issuse

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#21]
Hi @radixdev,

We are having an issue with iOS build. Please see the attached image.

![screen shot 2018-04-20 at 5 34 08 pm](https://user-images.githubusercontent.com/16328655/39036588-50359e14-44c1-11e8-88ea-9daa8e4f9969.png)

**Comment by Bucimis** [comment]
Hi @asangadev,

Were SDWebImage and FLAnimatedImage added to the "Embedded Binaries" section of Xcode? If not, could you try doing that?

Thanks,
Braze SDK Engineering

**Comment by asangadev** [comment]
Hi there,

Thanks for the reply. Still no luck. Please see below.

![screen shot 2018-04-23 at 10 00 45 am](https://user-images.githubusercontent.com/16328655/39101455-575c647a-46dd-11e8-8ba6-75d87534f848.png)

![screen shot 2018-04-23 at 10 01 03 am](https://user-images.githubusercontent.com/16328655/39101456-578a989a-46dd-11e8-9027-0611902fa59e.png)

**Comment by radixdev** [comment]
Can you also add `Appboy_iOS_SDK.framework" as an embedded binary as well?

**Comment by asangadev** [comment]
This is working now. But we don't see ant usage data in dashboard. I will email support. 
Thank you.
