### ISSUE TITLE
sample-project - Android integration issues

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#22]
Hi guys,

We are started to test the app on _Android_ and having some issues which we don't understand. We need you help here.

01. Cloned the sample-project and changed the <preference name="com.appboy.api_key" value="XXX-XXX-XXX-XXX" /> to our new API key.

02. Change the config.xml with <plugin name="cordova-plugin-appboy" spec="https://github.com/appboy/appboy-cordova-sdk#master" />

03. Complied the SDK with Adobe Phonegap Build.

04. Setup a test "News Feed" in dashboard (this feed is active and available for all Android audience).

05. Launched the sample-project and tapped on "Launch News Feed". We are getting "Network Error" issue at this stage.

06. Changed the <preference name="com.appboy.api_key" value="XXX-XXX-XXX-XXX" /> to your default 7ef72382-b92f-4258-9be9-9e19e92f3bf1.

07. Re-complied the app with Adobe Phonegap Build. This time "Launch News Feed" worked with your sample feeds.

08. Changed the <preference name="com.appboy.api_key" value="XXX-XXX-XXX-XXX" /> to our new API key again.

09. Complied the SDK with Adobe Phonegap Build.

10. Now, the "Launch News Feed" showing the old news feeds that related to your 7ef72382-b92f-4258-9be9-9e19e92f3bf1 APP key. We have clear the SDK data and uninstall the app and re installed multiple time to see the local storage is playing with us. We have no idea what is going on.

**QUESTIONS:**

01. We don't see App Usage data in dashboard. Could you please help us with this troubleshoot?

02. Are you guys still working on the GEOFence feature? We can see some updates in geofance-branch but not merged to the master branch yet.

Thanks!

**Comment by radixdev** [comment]
Can you email this over to support@braze.com? We'd be better able to handle this question.

As for the geofence feature, we maintain a separate branch for Geofences since there are [some static configuration values](https://github.com/Appboy/appboy-cordova-sdk/blob/geofence-branch/plugin.xml#L42-L47) that cannot be switched on/off in Cordova and thus need to be in a separate branch.

**Comment by radixdev** [comment]
Yes. Both iOS and Android have geofences supported for that branch.

**Comment by asangadev** [comment]
The main reason was the endpoint. We had to include this in config.xml
```
<platform name="ios">
<preference name="com.appboy.ios_api_endpoint" value="sdk.iad-03.braze.com" />
</platform>
```


```
<platform name="android">
<preference name="com.appboy.ios_api_endpoint" value="sdk.iad-03.braze.com" />
</platform>
```
