### ISSUE TITLE
Android - Obtain Location Permissions from the End User

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#23]
Hi there,

The sample android app works perfectly fine now and doing some geofence tests.

The location service permission prompt not showing during the app load and no location service permission granted to the app.

As per: https://www.braze.com/documentation/Android/#locations--geofences I can see below conditions in the .java file.

```
// Get location permissions, if we need them
if (cordova.hasPermission(LOCATION_PERMISSION)) {
     AppboyLocationService.requestInitialization(mApplicationContext);
} else {
    // Request the permission
    cordova.requestPermission(this, LOCATION_REQUEST_CODE, LOCATION_PERMISSION);
}
```

I'm using my own REPO here (the geofence branch is merged to master on this): https://github.com/asangadev/appboy-cordova-sdk

The **cordova.requestPermission()** not triggering. What I'm doing wrong here? Could you please advise?

Do I need below plugin to be installed?
```
<plugin name="cordova-plugin-geolocation" version="^2.1.0" />
```

**Comment by radixdev** [comment]
Using our cordova sample app on the geofences branch, I get the location permissions prompt.

Looking at your fork, the `plugin.xml` isn't properly setup for geofences.

See the [original](https://github.com/Appboy/appboy-cordova-sdk/blob/geofence-branch/plugin.xml) and [your version](https://github.com/asangadev/appboy-cordova-sdk/blob/master/plugin.xml).

For example, these location components are missing from your fork's `plugin.xml`.

![image](https://user-images.githubusercontent.com/2373546/39440976-8d76ccf6-4c7a-11e8-8944-98b2aa01bcc0.png)

![image](https://user-images.githubusercontent.com/2373546/39441011-9b3342f2-4c7a-11e8-802f-c453847e0abc.png)

**Comment by asangadev** [comment]
Sorry, It was my bad. Had an issue with the merge. Works perfect fine.

I've red the documentation about the Geofence and want to know how the user permissions (on iOS) will effects for real-time tracking.

https://www.braze.com/documentation/iOS/#locations--geofences

What if the user only grant "while using the app" (NSLocationWhenInUseUsageDescription)? 

01. The tacking will not work on app close (not in the background)?

02. During what events/stages the app will send most recent location to the dashboard?
