### ISSUE TITLE
Firebase Cloud Messaging

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#25]
Hi guys,

Is the SDK have the support for Firebase Cloud Messaging? If not, do we have an ETA?

**Comment by radixdev** [comment]
We currently do not have support for FCM in the Cordova SDK. However, given the upcoming GCM removal, this is a high priority for us.

**Comment by radixdev** [comment]
FCM support has been added as of SDK 2.5.1
