### ISSUE TITLE
Phonegap 8.0.0 Andoid build issue 

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#27]
Hi there,

We are having issues with PUSH registrations (not receiving PUSH) if we build the platform with Phonegap V 8.0.0 (Same results with local and cloud builds)

`<preference name="phonegap-version" value="cli-8.0.0" />`

We have changed the config.xml to below:
`<resource-file src="google-services.json" target="app/google-services.json" />`

It worked with phone gap 7.1.0 build. With 7.1.0 we have used:
`<resource-file src="google-services.json" target="google-services.json" />`

Could you please advice?

**Comment by radixdev** [comment]
1. What version of the Cordova SDK are you using?
2. Can you enable verbose logging (see https://www.braze.com/documentation/Cordova/Android_and_FireOS/#configure-the-plugin `<preference name="com.appboy.android_log_level" value=0 />`) and send the logcat output after running the app?
3. Can you share your config.xml here?

**Comment by asangadev** [comment]
We have fixed the issue by doing below:

Remove "com.appboy.android_fcm_sender_id" & "com.appboy.firebase_cloud_messaging_registration_enabled" from the Cordova config.xml, then create an "appboy.xml" in the app/src/main/res/values folder and add "com_appboy_firebase_cloud_messaging_registration_enabled" as a boolean and also "com_appboy_firebase_cloud_messaging_sender_id" as a string.

The documentation:
 https://www.braze.com/documentation/Android/#step-2-configure-token-registration
