### ISSUE TITLE
Session Starts Automatically with Cordova SDK

### ISSUE THREAD

**Issue by sourjam** [Appboy/appboy-cordova-sdk#29]
Hi,

We have some feedback on the Android cordova plugin where a session begins automatically before we can properly identify the user. Would it be possible to include a manual method of starting a session that way we can check if the user has a preexisting account with us?

Thanks,
Jim

**Comment by radixdev** [comment]
Hi @sourjam ,

I've added this suggestion to our cordova wrapper roadmap. In the meantime, you can modify the [android plugin](https://github.com/Appboy/appboy-cordova-sdk/blob/master/src/android/AppboyPlugin.java#L323-L333) to not automatically open a session by removing the highlighted section.

**Comment by sourjam** [comment]
Hey @radixdev thanks so much for the fast response! Looking forward to the update :)
