### ISSUE TITLE
Flush custom events manually

### ISSUE THREAD

**Issue by ronkot** [Appboy/appboy-cordova-sdk#30]
Feature request:

We'd need to react rapidly to certain braze custom events. The default lazy sending is too slow and unpredictable for our purposes, so we'd like to use manual event flushing. iOS and Android SDKs seem to offer API for this (`flushDataAndProcessRequestQueue` and `RequestImmediateDataFlush`). Unfortunately, this functionality isn't yet available via cordova plugin.

Could it be possible to bring manual data flushing to cordova plugin as well?

**Comment by radixdev** [comment]
Hello @ronkot ,

Thanks for filing this issue. We've added this as a high priority item on our roadmap. I can provide an update on this issue once the issue is fixed.

**Comment by radixdev** [comment]
Hi @ronkot ,

Cordova version 2.8.0 is now live. The method is `requestImmediateDataFlush()` on the plugin for both iOS and Android. Please let me know if this fixes your issue.

Julian

**Comment by hkellock** [comment]
Thanks @radixdev ! I removed a ticket related to this from our icebox. I'll let you know if this fixes our issue when we have time to work on this again.
