### ISSUE TITLE
App crash on Android

### ISSUE THREAD

**Issue by ericphamhoang** [Appboy/appboy-cordova-sdk#31]
Hi Braze,

I've developed and built my app using Cordova 2 months ago. There's no issue building and deploying it on Android. Unfortunately, today when I tried to build another version I found out that the app crashed every time it receive push notification.

I've tried reverting my app code to the previous version to ensure that there's nothing wrong in my new code. However it still crashed. 

Other braze functions (register users, track users) still work. 

Could you please help us on this?

------

Build version: 

phonegap 8.2.1
gradle 4.1 (Android Studio)

plugin cordova-plugin-appboy version 2.7.0 #master

**Comment by radixdev** [comment]
Hi @ericphamhoang ,

1. How are you integrating push? Firebase?
2. Can you provide the stacktrace of the crash?
3. Can you provide verbose logs leading up to the crash? See https://www.braze.com/docs/developer_guide/platform_integration_guides/cordova/android_and_fireos/initial_sdk_setup/#setting-extra-configuration and set `com.appboy.android_log_level` to `0`. Then, share that logcat here.

**Comment by ericphamhoang** [comment]
1. Yep, we use firebase push
2. We will send you a logcat today. Atm the version 2.5.1 works fine. However it asks for GeoFencing? Have no idea but this is SO UNNECCESSARY and waste my time testing it ^_^!

**Comment by jakejarrett** [comment]
This occurs for me on cordova 8.0.0 too, everything else seems to be working fine, just receiving notifications on android 8/9 (only ones i've tested so far) causes the app to crash (Haven't got log files at this moment, if you need them i can try again and get them)

Some notes;
## Cordova version
jake@jake-laptop ~/dev/Web/PhoneApp ±feature/braze-integration⚡ » cordova --version                                                                                                                                                                                   
8.0.0

## Plugins used in app
```
<plugin name="cordova-plugin-whitelist" spec="1" />
    <plugin name="cordova-plugin-globalization" spec="^1.0.7" />
    <plugin name="cordova-plugin-dialogs" spec="^1.3.3" />
    <plugin name="cordova-plugin-network-information" spec="^1.3.3" />
    <plugin name="cordova-plugin-nativestorage" spec="^2.2.2" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-app-version" spec="^0.1.9" />
    <plugin name="cordova-plugin-file-opener2" spec="^2.0.19" />
    <plugin name="cordova-plugin-spinner-dialog" spec="^1.3.1" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="cordova-plugin-hockeyapp" spec="^5.1.2" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.1">
        <variable name="GEOLOCATION_USAGE_DESCRIPTION" value="(Some description)" />
    </plugin>
    <plugin name="cordova-android-support-gradle-release" spec="^1.3.0">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-fingerprint-aio" spec="^1.3.8">
        <variable name="FACEID_USAGE_DESCRIPTION" value="(description for app)" />
    </plugin>
    <plugin name="cordova-plugin-google-analytics" spec="^1.8.6">
        <variable name="GMS_VERSION" value="16.0.0" />
    </plugin>
    <plugin name="cordova-plugin-appboy" spec="https://github.com/appboy/appboy-cordova-sdk#master" />
```

## Braze/AppBoy config details
```
<preference name="com.appboy.api_key" value="MY_API_KEY" />
        <preference name="com.appboy.firebase_cloud_messaging_registration_enabled" value="true" />
        <preference name="com.appboy.android_fcm_sender_id" value="MY_FCM_ID" />
        <preference name="com.appboy.android_api_endpoint" value="URL" />
        <custom-config-file mode="add" parent="/*" target="AndroidManifest.xml">
            <receiver name="com.appboy.AppboyFcmReceiver" permission="com.google.android.c2dm.permission.SEND">
                <intent-filter>
                    <action name="com.google.android.c2dm.intent.RECEIVE" />
                    <category name="APP_NAME" />
                </intent-filter>
            </receiver>
        </custom-config-file>

**Comment by radixdev** [comment]
Hi @jakejarrett ,

Thanks for the extra information. We've identified the source of the crash and have released a fix in version 2.7.1. Please let me know if this solves your issue.

Thanks,
Julian

**Comment by jakejarrett** [comment]
Thanks @radixdev :+1: that solved the issue :smile:

**Comment by radixdev** [comment]
Hi @ericphamhoang 

Can you provide logcat of the crash? Can you also provide steps or a sample project that reproduces the "app crash instantly when opening"?

**Comment by ericphamhoang** [comment]
Hi @radixdev 

I've created a blank Phonegap app.

https://github.com/ericphamhoang/appboy-crash

 I tried building and running it on Android. All work fine. After installing the plugin using this guide: 

https://www.braze.com/docs/developer_guide/platform_integration_guides/cordova/android_and_fireos/initial_sdk_setup/

the app start crashing when I open it. 

My test device is Samsung S9 running on Android 8. Phonegap version is 8.2.2 

Last time I tried downgrading your plugin to version 2.6.0 then it seems to work. Not with this version. Also the version 2.7.0 add the geofencing (which I don't really need) into AndroidManifest.xml as well. 

I will try testing will several version and let you know. But it doesn't seem to future-proofed if you need to downgrade the plugin version

My suggestion is putting #beta tag instead of #master for new versions. This will help us in next builds as it's time consuming running back and forth testing an unstable version like this

**Comment by jakejarrett** [comment]
@ericphamhoang using `#master` as the tag, means you're pulling the *very* latest from the git repo (aka, treat it like it *is* beta), instead you should be targeting versions directly (EG/ using this would be considered safe `<plugin name="cordova-plugin-appboy" spec="https://github.com/appboy/appboy-cordova-sdk#2.7.1" />`)

**Comment by ericphamhoang** [comment]
@jakejarrett that's what I did to install version 2.6.0, you can check my previous comment (before your comment)

Also if you still have any doubt you can check my sample project 
https://github.com/ericphamhoang/appboy-crash
(or basically create a new phonegap project and add this plugin)

**Comment by ericphamhoang** [comment]
Hi @radixdev 

I just built again yesterday and it seems to work
