### ISSUE TITLE
Unable to register for push notifications on iOS

### ISSUE THREAD

**Issue by jakejarrett** [Appboy/appboy-cordova-sdk#32]
Hey,

Seems that the latest version of the SDK doesn't allow registering for push notifications on iOS?

Calling `AppboyPLugin.registerAppboyPushMessages()` returns the following error in xcode; `ERROR: Methid 'registerAppboyPushMessages:' not defined in Plugin 'AppboyPlugin'`

This is using `2.7.1`

**Comment by radixdev** [comment]
[That method is marked as Android only.](https://github.com/Appboy/appboy-cordova-sdk/blob/f25d0fcaed381aa625835f74a51d9c6a16167e2e/www/AppboyPlugin.js#L42-L54) Please follow the [Cordova iOS push integration](https://www.braze.com/docs/developer_guide/platform_integration_guides/cordova/ios/initial_sdk_setup/) to setup push on iOS.

**Comment by jakejarrett** [comment]
Yeah my bad, the error was that my ios config wasn't using the `com.appboy.ios_api_endpoint` preference.
