### ISSUE TITLE
dyld: Library not loaded: 

### ISSUE THREAD

**Issue by jamesyoon11** [Appboy/appboy-cordova-sdk#33]
Hi,

For iOS build, the following error occurred when it ran the app.

dyld: Library not loaded: @rpath/FLAnimatedImage.framework/FLAnimatedImage
  Referenced from: /Users/xxxx/Library/Developer/CoreSimulator/Devices/B9938792-2064-41EF-9879-2621F73C7719/data/Containers/Bundle/Application/168C7F7E-5747-49D4-BCAA-B79367316751/XXXX
Reason: image not found

I think it is because FLAnimatedImage.framework, Appboy_iOS_SDK.framework, and SDWebImage.framework are dynamic framework but it is added as static. So it should change plugin.xml to embed frameworks into an app bundle, so it can be dynamically loaded at runtime.

    <framework src="src/ios/frameworks/iOS/FLAnimatedImage.framework" custom="true" embed="true"/>
    <framework src="src/ios/frameworks/iOS/Appboy_iOS_SDK.framework" custom="true" embed="true"/>
    <framework src="src/ios/frameworks/iOS/SDWebImage.framework" custom="true" embed="true"/>

Or, please replace the frameworks with static frameworks.

Best,

**Comment by radixdev** [comment]
Hi @jamesyoon11 & @sean-browze ,

Thank you for filing this issue. Does adding `embed="true"` solve your issue? Our standard recommendation is to add those frameworks to the "Embedded Frameworks" section in XCode but it appears the `embed` flag does the same thing.

**Comment by jamesyoon11** [comment]
Hi @radixdev ,

Yes, it resolves the issue. `embed` is available cordova 7 or later (https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#framework) to support dynamic framework to be added to the "Embedded Frameworks".

**Comment by sean-browze** [comment]
@radixdev that seems to resolve the issue for me too

**Comment by radixdev** [comment]
Thanks for the response. I've added this to our internal Cordova roadmap. In the meantime, you'll have to either edit the `plugin.xml` or add the frameworks to the embedded section in XCode.

**Comment by radixdev** [comment]
Hi @jamesyoon11 & @sean-browze ,

Braze Cordova version 2.8.0 is now released. The xml `embed="true"` is now included in the `plugin.xml`. Please let me know if this fixes your issue.

Julian
