### ISSUE TITLE
Weird number conversion for iOS

### ISSUE THREAD

**Issue by jamesyoon11** [Appboy/appboy-cordova-sdk#35]
Hello, 

When I pass a number to custom event properties, the number is converted to weird decimal numbers. For example, I pass the value as 4.95 like

AppboyPlugin.logCustomEvent("AddToCart", {
   "Cart Value": 4.95,
   "Cart Item Name": "Spicy Chicken Bites 5 pack"
});

It is converted to 4.9500000000000002 by appboy SDK. 

This is a Charles Proxy log

<img width="568" alt="charles_proxy" src="https://user-images.githubusercontent.com/13875691/55256308-03ecf900-521a-11e9-9a2e-5a0f0538bee7.png">

And, the Braze dashboard shows it as 4.9500000000000002 as well.

![event_user_log](https://user-images.githubusercontent.com/13875691/55256546-7e1d7d80-521a-11e9-8a98-388161993dae.png)

Can you please look into why the number is converted like this?

Thanks,

**Comment by radixdev** [comment]
Hi @jamesyoon11 ,

We will investigate why your issue. However, this just looks like standard Javascript floating point weirdness and not signs of a larger issue.

Julian

**Comment by jamesyoon11** [comment]
Hi @radixdev 

I don't think this is because of a  javascript floating point problem. I already parse the number with 2 decimal places in javascript side.

var price = parseFloat(price.toFixed(2));

And, in the iOS debugger, I can see the price is correctly 2 decimal places number until [Appboy logCustomEvent](https://appboy.github.io/appboy-ios-sdk/docs/interface_appboy.html#abb8c5e47a270fc7ad0b20630ce073f30) is called.

<img width="764" alt="ios_debug" src="https://user-images.githubusercontent.com/13875691/55295583-9ed50700-53c3-11e9-84a7-47ec44411d02.png">

If it is not a large issue, can you please confirm that 4.95 and 4.9500000000000002 are equal when we perform custom event option?

<img width="721" alt="Screen Shot 2019-03-31 at 3 00 38 PM" src="https://user-images.githubusercontent.com/13875691/55295770-ed83a080-53c5-11e9-8e75-4b807fc5efbc.png">


Best,

**Comment by radixdev** [comment]
Thanks for the extra information. Our iOS team is investigating and we will update you once we determine next steps.

**Comment by radixdev** [comment]
Hi @jamesyoon11 ,

An upstream patch in https://github.com/Appboy/appboy-ios-sdk/blob/3.14.1/CHANGELOG.md#fixed was introduced and later added here in Cordova SDK version 2.10.0. We're [confident](https://github.com/Appboy/appboy-cordova-sdk/blob/master/sample-project/www/js/index.js#L97-L100) this fixes your issue.

Thanks,
Julian
