### ISSUE TITLE
Android purchase price

### ISSUE THREAD

**Issue by jamesyoon11** [Appboy/appboy-cordova-sdk#36]
For Android, the purchase price is converted to long number (ex 4.95 is converted to 4).

https://github.com/Appboy/appboy-cordova-sdk/blob/master/src/android/AppboyPlugin.java#L170

So please update 

new BigDecimal(args.getLong(1))

to 

new BigDecimal(args.getDouble(1))

**Comment by radixdev** [comment]
Hi @jamesyoon11 ,

We've created an issue to address the price on Android. Thank you for filing!

Julian

**Comment by radixdev** [comment]
Fixed in 2.9.0
