### ISSUE TITLE
Automatic ios config fails

### ISSUE THREAD

**Issue by ronkot** [Appboy/appboy-cordova-sdk#39]
We're using appboy cordova plugin for our ios and android projects. Currently we're using plugin version 2.6.0 with cordova-ios version 4.5.5. Now we'd like to update to the latest appboy plugin version 2.10. As a part of the update we needed to generate the ios project with most recent cordova-ios version 5.0.1. We didn't change how appboy values were configured in our cordova config.xml.

Now, when I start the app, I see an error in debug view: `[APPBOY] invalid_api_key`. I think the api key and custom endpoint should have been configured automatically according to our cordova config.xml as it was with our previous setup. It seems that I can configure these manually according to https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/initial_sdk_setup/#step-4-updating-your-app-delegate.

We'd definitely prefer automatic config as we're building every release from scratch and configuring things manually is laborious and error-prone. Do you have any tips how to make automatic config to work?

**Comment by radixdev** [comment]
Hi @ronkot ,

The automatic configuration is done in https://github.com/Appboy/appboy-cordova-sdk/blob/master/src/ios/AppboyPlugin.m#L51-L54. I'm not aware of any recent changes to that flow. Can you confirm that:
1. The AppboyPlugin is running
2. The values in that automatic configuration match that of your manual configuration.

This should help us nail down the exact issue.

Thanks,
Julian

**Comment by radixdev** [comment]
Hi @ronkot ,

This is a bug in the 2.10.0 release of our Cordova SDK. The `cordova-ios@5.0.1` upgrade is just a red herring. You can expect a fix very shortly.

**Comment by radixdev** [comment]
Hi @ronkot ,

This should be fixed in 2.10.1 of the SDK. Please let us know if this fixes your issue.

Julian

**Comment by ronkot** [comment]
Hi @radixdev,

It seems the issue is fixed now, and everything works as expected. Thanks for a rapid fix! 😎
