### ISSUE TITLE
Feature Request: Unread Newsfeed Count

### ISSUE THREAD

**Issue by bendalton** [Appboy/appboy-cordova-sdk#4]
It would be great to get the unread count for displaying in a badge, etc.

**Comment by briancaw** [comment]
Hi @bendalton  

Thanks for this feedback.  We'll aim to incorporate this in our next release which we're aiming to be in the next 6 weeks.

Please let us know if you have any further comments/questions.

Thanks,
Brian

**Comment by radixdev** [comment]
Hey @bendalton 

Our Cordova 2.0.0 release includes getters for the number of unread newsfeed cards. Please see our sample project for [an example](https://github.com/Appboy/appboy-cordova-sdk/blob/master/sample-project/www/js/index.js#L167).

Thanks,
Julian
