### ISSUE TITLE
Android Network error

### ISSUE THREAD

**Issue by ericphamhoang** [Appboy/appboy-cordova-sdk#40]
I just found that when you installed and removed Braze, it also remove the android permission INTERNET on AndroidManifest.xml
I've added the permission manually but just feel obligated to leave a small note just in case someone run into this issue
<uses-permission android:name="android.permission.INTERNET" />

**Comment by radixdev** [comment]
Hi @ericphamhoang ,

Sorry you've ran into this issue. Do you have an alternative to including our necessary/relevant permissions in the `plugin.xml`?
