### ISSUE TITLE
Android - Not Registering for Push

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#41]
@radixdev 

Hi there, I'm having an issue with Android Studio (V 3.4.2) and Gradle 5.5.1. This happened after I upgrade the Android Version to the latest (this worked before without any issues). I tried again by down grading the software and Gradle but no luck.

The device is registering for the events such as "Last Used". Meaning the device can receive in-app messages. But no android platform under "Push Registered For".

I have attached the logcat and my configs. Could you please help me on this? without knowing this, I have released a new version to the Play store for 100% audience. Now people are not in the subscribed list. 

<img width="1013" alt="Screen Shot 2019-07-24 at 11 28 26 am" src="https://user-images.githubusercontent.com/16328655/61758021-65a72380-ae06-11e9-8b23-2aa329306416.png">

<img width="1245" alt="Screen Shot 2019-07-24 at 11 27 14 am" src="https://user-images.githubusercontent.com/16328655/61758023-65a72380-ae06-11e9-9510-d640aade777e.png">

[logcat.txt](https://github.com/Appboy/appboy-cordova-sdk/files/3424617/logcat.txt)

**Comment by Bucimis** [comment]
@asangadev A few thoughts:
1) we recommend renaming your `app.boy.xml` file to `appboy.xml`
2) The firebase sender Id in the `app.boy.xml` file looks different than the one configured in `config.xml`
3) Could you post logcat from the latest version of the Cordova SDK? It should use Android SDK 3.2.2.

**Comment by asangadev** [comment]
@Bucimis 

1. renamed
2. fixed
3. attached

[logcat_v2.txt](https://github.com/Appboy/appboy-cordova-sdk/files/3424862/logcat_v2.txt)

**Comment by asangadev** [comment]
Fixed it by manually updating the java file
