### ISSUE TITLE
Icon Drawable

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#42]
Hi there,

I've created the icons using the: http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=image&source.space.trim=1&source.space.pad=0&name=notification_icon

How can we add this icon to the app? I'm on Android Studio and wanting to know how to assign the values for RESOURCE_ENTRY_NAME_FOR_ICON_DRAWABLE?

I tried uploading the png to **res > drawable** folder and adding **@drawable/notification_icon** But no luck.

`<preference name="com.appboy.android_small_notification_icon" value="RESOURCE_ENTRY_NAME_FOR_ICON_DRAWABLE" />`

**Comment by radixdev** [comment]
Can you try following `https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/configuration/AppboyConfig.Builder.html#setSmallNotificationIcon-java.lang.String-` and setting the resource entry name that way?

**Comment by asangadev** [comment]
No luck!

**Comment by asangadev** [comment]
Fixed this by making all the icons transparent.
