### ISSUE TITLE
Issue with the plugin installation

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#43]
Hi @radixdev ,

I'm getting below error on a blank Cordova project.

cordova plugin add https://github.com/appboy/appboy-cordova-sdk#master

`Installing "cordova-plugin-appboy" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Failed to install 'cordova-plugin-appboy': undefined`

**Comment by radixdev** [comment]
Hi @asangadev ,

Can you share the modification you made to the plugin?

**Comment by asangadev** [comment]
Hi @radixdev, 

You can find it here: https://github.com/asangadev/appboy-cordova-sdk
