### ISSUE TITLE
iOS - Bluetooth Permission

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#44]
Hi @radixdev 

Is this plugin requires the Bluetooth Permission? I have noticed our app is asking for Bluetooth Permissions on iOS 13? I understands this is a new iOS requirement if the app uses Bluetooth.

Is this something to do with the Braze requirements? If so, is it possible to remove/disable all the Bluetooth functionalities? So the app don't need the Bluetooth Permissions? 

Please advise/

**Comment by radixdev** [comment]
Hi @asangadev ,

We don’t use bluetooth in our SDK. If you don’t use it in your app, you should check if you have another SDK or plugin that uses it.

**Comment by asangadev** [comment]
Thanks @radixdev
