### ISSUE TITLE
iOS - Push notification when the app is open 

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#45]
Hi @radixdev,

Is it possible to receive a push notification while the app is running and open? Please advise.

**Comment by radixdev** [comment]
Hi @asangadev ,

Have you tried routing this through support@braze.com? This seems better suited to that avenue, unless you're describing a bug.

**Comment by asangadev** [comment]
@radixdev, cheers! they got back to me with below: 

https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/integration/#step-5-enable-push-handling

**Comment by asangadev** [comment]
Hi @radixdev,

I know this is not a bug report. This is a feature request from us. Do you think you can show us how to implement below with current plugin for iOS?


<img width="924" alt="Screen Shot 2019-10-03 at 11 04 11 am" src="https://user-images.githubusercontent.com/16328655/66092024-8db4bf00-e5cd-11e9-90de-04872f2f8da2.png">

**Comment by radixdev** [comment]
Hi @asangadev ,

We're adding this to our Cordova product roadmap. Thank you for bringing this to our attention.

**Comment by asangadev** [comment]
Cheers!

**Comment by asangadev** [comment]
@Bucimis ,

Do you guys have an update on this or any instructions how to enable this for iOS users? Please advise.

**Comment by asangadev** [comment]
@Bucimis 

Any update?

**Comment by Bucimis** [comment]
@asangadev we're aiming to have this in 4 weeks-ish

**Comment by xueligoh** [comment]
Hihi, we are also not receiving the push notification when the app is running in the foreground for android. Possible to check if this is also not a feature available for android currently? And if so, whether it is also included in the roadmap for android? Thanks in advanced!

**Comment by asangadev** [comment]
@xueligoh Actually I never had that foreground issue with Android. It's working for me on Android.

**Comment by Bucimis** [comment]
@xueligoh +1 to @asangadev, this should already work on Android

**Comment by asangadev** [comment]
@Bucimis any progress update here? We would love to add this feature to our app soon. 

This feature is a must have for our iOS users. 

Please keep us in the loop.

**Comment by Bucimis** [comment]
@asangadev we're expecting to have support for this in the next 4-6 weeks

**Comment by asangadev** [comment]
@Bucimis @radixdev 

Thanks guys! This is working now with: https://github.com/Appboy/appboy-cordova-sdk/blob/master/CHANGELOG.md#2160
