### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWeb Worning!

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#50]
Hi @Bucimis,

We are getting below warning:

**ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020.**

I've found the UIWeb is used in below frameworks.

- Appboy_iOS_SDK
- FLAnimatedImage
- SDWebImage

Are you guys have a plan or solution at this stage?

**Comment by asangadev** [comment]
Foumd the soljution here: https://github.com/Appboy/appboy-ios-sdk/issues/198#issuecomment-530117731

**Comment by Bucimis** [comment]
@asangadev you got it right :) One thing to keep in mind while upgrading - make sure not to use Braze Cordova SDK versions `2.11.0` or `2.11.1` as those contain known issues. We recommend using our latest release https://github.com/Appboy/appboy-cordova-sdk/blob/master/CHANGELOG.md#2130

**Comment by asangadev** [comment]
@Bucimis Cheers! Thanks for the info! :)
