### ISSUE TITLE
No push subscription state update via the app settings

### ISSUE THREAD

**Issue by jamesyoon11** [Appboy/appboy-cordova-sdk#53]
For iOS, the initial push subscription state is 'Subscribed'. And, when the push permission prompt is displayed, I clicked 'Allow' so the push subscription state is moved to 'Opted-In'. This is what I expected so it's good. 

![Screen Shot 2020-05-04 at 5 00 11 PM](https://user-images.githubusercontent.com/13875691/81024683-02ccc900-8e29-11ea-9420-7bb19fd86000.png)

However, I disabled the notification permission via the app settings but the push subscription state is still 'Opted-In' even if I tried to close and reopen the app multiple times.

<img width="330" alt="Screen Shot 2020-05-04 at 5 02 40 PM" src="https://user-images.githubusercontent.com/13875691/81024696-1710c600-8e29-11ea-8fac-361d920b1ecb.png">

How dose it update to 'UnSubscribed' when the permission authorization is denied via the app settings?

**Comment by radixdev** [comment]
This is expected behavior. After you opt-in at a user level, the only way to mark that user as unsubscribed, or otherwise change from `Opted In`, is through our user subscription methods.

**Comment by jamesyoon11** [comment]
@radixdev thank you for the answer. I thought it was not automatically done and we didn't need to implement it on our own. Okay.. So, is the following assumption correct when implementing subscription methods?

- UNAuthorizationStatusNotDetermined: Subscribe
- UNAuthorizationStatusDenied: Unsubscribe
- UNAuthorizationStatusAuthorized: Opted In

**Comment by Bucimis** [comment]
@jamesyoon11 that looks like a good mapping to me.

**Comment by jamesyoon11** [comment]
Thank you for the prompt reply @Bucimis. Closing the issue.
