### ISSUE TITLE
New SDK updates for iOS/Andriod

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#54]
Hi guys,

Any plans to update the SDKs soon?

iOS: 3.26.1
Android: v8.1.0

Please let us know.

**Comment by radixdev** [comment]
Hello @asangadev ,

We should have updates to the SDKs fairly soon. Thank you for your patience.

**Comment by asangadev** [comment]
Thanks for the latest update guys! Appreciate it!
