### ISSUE TITLE
Android: Android keyboard not appearing on input focus - with IAM

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#55]
Hi guys,

We have an issue with the IAM messages (any type).

On Android, after you close an IAM, keyboard not appearing on any input focus (specially type=text).

SDK: 8.1.0 
Plugin: 2.16.0

It worked with Plugin V: 2.5.1 (we then jumped from 2.5.1 to 2.15.0 during our updates). The issue is on V 2.15.0 too.

UPDATE: I have also tested this with a blank Cordova App. Installed the latest AppBoy Plugin. Set up an IAM. Please see below

Note: Issue is not on Android API28 and above

![Screen Shot 2020-09-01 at 7 49 54 pm](https://user-images.githubusercontent.com/16328655/91835203-69091180-ec8c-11ea-88ed-dbb85aa79237.png)

The keyboard is not showing after closing the IAM.

![Screen Shot 2020-09-01 at 7 50 07 pm](https://user-images.githubusercontent.com/16328655/91835208-6b6b6b80-ec8c-11ea-928e-b67560793af3.png)

**Comment by asangadev** [comment]
@Bucimis @radixdev Is this something that I need to coordinate with the Andoird SDK team/repo?

**Comment by radixdev** [comment]
Hi @asangadev ,

Apologies for the late response. Can you provide verbose logcat logging of the flow you described? This would help us with debugging. 

To enable verbose logging, set `"com.appboy.android_log_level"` to 0 as per https://www.braze.com/docs/developer_guide/platform_integration_guides/cordova/android_and_fireos/initial_sdk_setup/#setting-extra-configuration

**Comment by asangadev** [comment]
@radixdev please see attached.
[logcat.txt](https://github.com/Appboy/appboy-cordova-sdk/files/5192688/logcat.txt)

**Comment by radixdev** [comment]
Hi @asangadev ,

This might be an issue with the IAM view wrapper taking focus and returning it back to the WebView after the IAM displays (see line 1033). Does the keyboard appear after tapping on the text field?

I would recommend following https://www.braze.com/docs/developer_guide/platform_integration_guides/android/in-app_messaging/customization/#setting-a-custom-view-wrapper-factory and overriding the focus related logic. [Look for usages of this variable](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/java/com/appboy/ui/inappmessage/DefaultInAppMessageViewWrapper.java#L50) in our default view wrapper.

**Comment by asangadev** [comment]
@radixdev 

Thanks! Not getting the keyboard (after tapping the on the text field) after closing the IAM. 

Is this something you guys can fix with your future DSK releases?

**Comment by radixdev** [comment]
@asangadev A fix was just released in version 2.26.0 of the SDK.
