### ISSUE TITLE
Plugin activates "In-App Purchases" on iOS (14.1)

### ISSUE THREAD

**Issue by vandres** [Appboy/appboy-cordova-sdk#56]
After installing the plugin, our project has now "In-App Purchases" active as Capability. How can that be?

**Comment by Bucimis** [comment]
@vandres thanks for reporting, we've repro'd and are looking into a fix

**Comment by Bucimis** [comment]
@vandres if you go into your local copy of `plugin.xml`, and temporarily remove this line https://github.com/Appboy/appboy-cordova-sdk/blob/f34224ebf505f649065aacc127b26b7c280833be/plugin.xml#L52, does that solve the issue for you?

**Comment by vandres** [comment]
@Bucimis I will test it tomorrow, thanks for checking

**Comment by vandres** [comment]
@Bucimis Since we have an automated build system, removing it manually is of course no long term solution

**Comment by Bucimis** [comment]
@vandres yep, we tested the fix locally and it works for us, just wanted to confirm with you as well before releasing.

**Comment by vandres** [comment]
@Bucimis I can confirm, removing that line, removes the Capability. Silly question: Are there other frameworks which are included and we don't need? Like "AdSupport"

**Comment by Bucimis** [comment]
@vandres thanks for the feedback, we'll evaluate deleting other potentially unneeded frameworks as well
