### ISSUE TITLE
SetLanguage

### ISSUE THREAD

**Issue by vandres** [Appboy/appboy-cordova-sdk#58]
I am seeing, that the Cordova SDK is lacking the `AppboyPlugin.setLanguage(language: string)`. Is there any plan to support that?

We are planning to support 11 languages. How to do that without this option?

**Comment by radixdev** [comment]
Hi @vandres ,

We've added a story to our backlog to support that method.

**Comment by radixdev** [comment]
Added in 2.19.0 of the SDK.
