### ISSUE TITLE
requestContentCardsRefresh - successCallback and errorCallback are undefined

### ISSUE THREAD

**Issue by drewrygh** [Appboy/appboy-cordova-sdk#60]
This requestContentCardsRefresh does not take any arguments, but it references a successCallback and errorCallback. 

https://github.com/Appboy/appboy-cordova-sdk/blob/master/www/AppboyPlugin.js#L359

**Comment by Bucimis** [comment]
@drewrygh are you seeing build warnings or are you hoping to have callbacks for requestContentCardsRefresh?

**Comment by drewrygh** [comment]
I'm not seeing any build warnings, just looking to be able to pass success/error callbacks to this method.

**Comment by radixdev** [comment]
Hi @drewrygh ,

Those callback references were added in error to the cordova plugin and will be removed. Adding callbacks to this method would have to first be accomplished in the native SDKs directly as a product request.
