### ISSUE TITLE
Android: Android keyboard not appearing on input focus - with IAM

### ISSUE THREAD

**Issue by jyoon11** [Appboy/appboy-cordova-sdk#73]
Hi,

We are having the same issue as https://github.com/Appboy/appboy-cordova-sdk/issues/55

FYI, our testing confirms that the issue happens for Andorid 8 and 8.1 only.

In the ticket, your recommendation for the issue is following braze.com/docs/developer_guide/platform_integration_guides/android/in-app_messaging/customization/#setting-a-custom-view-wrapper-factory and overriding the focus related logic. Look for usages of this variable in our default view wrapper.

However, our build is just fetching the cordova plugin from npmjs as it is and building without any customization.

So, can you please fix the issue on the SDK side?

Best,

**Comment by radixdev** [comment]
Hi @jyoon11 ,

We will look into native SDK changes to address this. Can you confirm which Braze Android and Cordova SDK versions you're using?

**Comment by radixdev** [comment]
Hi @jyoon11 ,

Thanks for the tip about the issue only appearing for Android 8 and 8.1. I could also confirm that happening. Upon more research, this is an issue with the Android OS Webview (https://issuetracker.google.com/issues/36915710) that is only fully resolvable with direct access to the Cordova Webview. I would recommend filing an issue with the Cordova Android team (https://github.com/apache/cordova-android/issues).

In the meantime, we've implemented a fix on Android but I would like to reiterate that it is only a partial solution as the core issue lies with the Android OS and Cordova itself.

**Comment by radixdev** [comment]
@jyoon11 A fix was just released in version 2.26.0 of the SDK.

**Comment by jyoon11** [comment]
> @jyoon11 A fix was just released in version 2.26.0 of the SDK.

@radixdev Thank you so much for taking care of fixing the issue. I really appreciate your quick response and lightning fast release.
