### ISSUE TITLE
Support Delaying Automatic Session Tracking for iOS 

### ISSUE THREAD

**Issue by ghobashy** [Appboy/appboy-cordova-sdk#75]
Hello,

I would like to request supporting Delaying Automatic Session Tracking for iOS, because currently its only supported in Android

`<preference name="com.appboy.android_disable_auto_session_tracking" value="true" />`

**Comment by Bucimis** [comment]
Hi @ghobashy 

Unfortunately, customizing session tracking is only available on Android at this time. On iOS, sessions are tracked automatically by the SDK after it is initialized, i.e. after `startWithApiKey` is called.
