### ISSUE TITLE
Error Building Android version latest appboy-plugin version

### ISSUE THREAD

**Issue by victor-frankfi** [Appboy/appboy-cordova-sdk#79]
Hi, I am getting the following error trying to use the latest version of your plugin.
Maybe I am misunderstanding how the android build process works.
According to Cordova official documentation we can see the following
![30AC3411-18EB-4091-BDD2-27F4CA0FA5E9](https://user-images.githubusercontent.com/97022928/173339949-66bb96f5-a568-403f-92c8-e62472e7b2c0.png)

**But when we take a look into cordova-plugin-appboy we have the following configuration:**
![6CA14DE4-A33A-407C-A3C1-34D320BC21F4](https://user-images.githubusercontent.com/97022928/173340216-b744ba90-8a04-4bcb-8527-a85e6a74d207.png)

**Meaning when i try to point the targetSdkVrersion=30 (according to Cordova official documentation) in my config.xml file i have the following error during the build process:**
![05F875B2-6D17-40BF-999C-2D91FB92E6B7](https://user-images.githubusercontent.com/97022928/173340565-25928805-1055-47a2-ba95-46d312a36875.png)

**If i change my targetSdkVersion to 31 I run into the following error:**
![D1B1159B-B504-4677-BD37-96BA6A563468](https://user-images.githubusercontent.com/97022928/173341539-4bea5abd-dad5-49a2-bb11-5117fd0f43f0.png)

**You can see more details in the follogin screenshot**
![3C889F07-4387-4A0A-B8E1-74514F7B8758](https://user-images.githubusercontent.com/97022928/173341411-c7e55466-ce6e-49cb-8764-8bb12d889437.png)

can anyone bring some light on my problem?
Thanks!

**Comment by radixdev** [comment]
Hi @victor-frankfi ,

Can you specify which version of the `cordova-android` dependency you're using?

**Comment by radixdev** [comment]
Hey @victor-frankfi ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
