### ISSUE TITLE
[Android] Ability to specify notification accent color and small icons

### ISSUE THREAD

**Issue by qimingfang** [Appboy/appboy-cordova-sdk#8]
According to the android docs, there are quite a few additional properties that we can specify, such as `com_appboy_push_small_notification_icon` and `com_appboy_push_large_notification_icon` and `com_appboy_default_notification_accent_color`

Whats the easiest way to add these in?

**Comment by radixdev** [comment]
Hey @qimingfang,

These settings are found in the appboy.xml file for Android. At the moment we don't support a graceful way of setting these values in Cordova.

For now, you can alter the appboy.xml file via editing the plugin.xml, [as seen here](https://github.com/Appboy/appboy-cordova-sdk/blob/master/plugin/plugin.xml#L45). To add resource files from the plugin.xml, please see [the cordova plugin documentation here](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#resource-file). Note that these settings would be reset every time the Appboy plugin gets synced.

**Comment by radixdev** [comment]
Hi @qimingfang,

If you have any further comments/questions regarding this issue, please feel free to update or re-open. Thanks again for raising this issue.
