### ISSUE TITLE
push registration - updates for Android 13

### ISSUE THREAD

**Issue by KirstenStake** [Appboy/appboy-cordova-sdk#81]
Hi Team,

With apps in the stores needing to accommodate Android 13 by November, is the plugin going to update/handle the new change around permissions for notifications for Android 13?

More information here:
https://developer.android.com/develop/ui/views/notifications/notification-permission

**Comment by radixdev** [comment]
Hi @KirstenStake ,

The Braze Cordova Android plugin is currently on Braze Android SDK version 21.0.0, which includes support for Android 13. See https://github.com/Appboy/appboy-cordova-sdk/blob/master/CHANGELOG.md#2300. We also have an internal story to add a "showPushPrompt" method on the cordova bridge itself specifically for Android 13 devices.

**Comment by KirstenStake** [comment]
@radixdev thank you for your quick response. Do you know when this internal story for the "showPushPrompt" method is planned to be released for the plugin?

**Comment by radixdev** [comment]
We're planning on having this available within the next 2 weeks. I'll update this issue once it's live.

**Comment by radixdev** [comment]
Hi @KirstenStake ,

This is now released in version 2.31.0 of the SDK.
