### ISSUE TITLE
Support for in app messages listeners.

### ISSUE THREAD

**Issue by rahulm2** [Appboy/appboy-cordova-sdk#82]
Is there a way we can add a callback listener for in app messages, just like the braze web-sdk?

**Comment by radixdev** [comment]
Hi @rahulm2 ,

Currently we only have documentation present at https://www.braze.com/docs/developer_guide/platform_integration_guides/cordova/cordova_integration/#in-app-messaging for In-App Message callbacks on Cordova.

**Comment by rahulm2** [comment]
@radixdev I forked and implemented a sample for android https://github.com/Appboy/appboy-cordova-sdk/compare/master...rahulm2:appboy-cordova-sdk:master. Can you help me on doing the same for IOS? 
The docs provided are not very clear, also i am not familiar with Objective C

**Comment by radixdev** [comment]
Hi @rahulm2 ,

We generally cannot support debugging custom integrations in the manner you're describing. I would recommend either emailing support@braze.com for filing a product request or taking a look at https://github.com/Appboy/appboy-ios-sdk.
