### ISSUE TITLE
The sample application just not work!

### ISSUE THREAD

**Issue by AntonnyAGS** [Appboy/appboy-cordova-sdk#84]
The sample application starts fine and runs on the IOS device. But when trying to send an event (like changing user) just doesn't work! There is nothing in the log, but the data is not sent to Braze. 

Running on:
Macbook M1 (IPhone 14 simulator - IOS 16)

Cordova 11

**Comment by Bucimis** [comment]
@AntonnyAGS the sample app must be configured to use your cluster endpoint URL and API key, otherwise it will not be able to succesfully connect to any Braze backend
