### ISSUE TITLE
Main field missing in package.json

### ISSUE THREAD

**Issue by fbolanos-shg** [Appboy/appboy-cordova-sdk#86]
Hello,

Im having issues trying to import the plugin into my code.
`Module not found: Error: Can't resolve 'appboy-cordova-sdk' in '/Users/fbolanos/Projects/sharegro/myapp/libs/util-analytics/src/lib'`

I fixed this by manually adding the `main` field to the package.json file.

How i fixed it:
_package.json_

{
  "name": "appboy-cordova-sdk",
  "version": "2.31.0",
  "main": "www/AppboyPlugin.js"
}

This works on my local environment but still crashes in production when the building task fetches the code from the current master branch for this plugin.
 
 Anybody knows about workarounds for this, or can it get fixed?
 
 Thanks

**Comment by radixdev** [comment]
Hi @fbolanos-shg ,

We're tracking this issue and will update you once we have a fix available. Can you confirm your cordova version and any other cordova/capacitor specific integrations?

**Comment by fbolanos-shg** [comment]
Hi @radixdev,

With the manual fix I am able to identify users, send In-App messages and register for push notifications.
I'm running an Ionic/capacitor app with typescript, this are some dependencies:

 "@awesome-cordova-plugins/social-sharing": "^5.37.3",
 "@capacitor-community/firebase-analytics": "^1.0.1",
 "@capacitor/app": "^1.1.1",
 "@capacitor/core": "^3.4.3",
 "@capacitor/push-notifications": "1.0.9",
 "@ionic-native/core": "^5.36.0",
 "@ionic-native/social-sharing": "^5.36.0",
 "@ionic/react": "^5.5.2",
 "appboy-cordova-sdk": "https://github.com/appboy/appboy-cordova-sdk#master",
 "appsflyer-capacitor-plugin": "^6.8.2",
 "cordova-plugin-x-socialsharing": "^6.0.3",
 "cordova-res": "^0.15.4",
 "es6-promise-plugin": "^4.2.2",
 "onesignal-cordova-plugin": "^3.0.3"

**Comment by radixdev** [comment]
Hi @fbolanos-shg ,

We've fixed this internally and will update you once it's released.

**Comment by radixdev** [comment]
Hi @fbolanos-shg ,

I've updated the `package.json` ahead of our next scheduled release. Please let us know if this fixes your issue!
